name: Deploy Identity Service to Render with Docker

on:
  push:
    branches:
      - main  # Trigger khi commit được đẩy lên nhánh chính

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Cài đặt Java (Spring Boot yêu cầu Java)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Bước 3: Build và test ứng dụng Spring Boot với Maven
      - name: Build and Test with Maven
        run: |
          mvn clean install -DskipTests=false  # Build và chạy tất cả các test